# Generated by Django 5.0.6 on 2024-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
